### ISSUE TITLE
Queue broken?

### ISSUE THREAD

**Issue by verdurin** [OpenStackCookbook/OpenStackCookbook#44]
Just ran the quick start instructions with today's snapshot and the Nova service isn't reporting back:

```
vagrant@controller:~$ nova list
ERROR (ConnectionError): HTTPConnectionPool(host='192.168.100.200', port=8774): Max retries 
exceeded with url: /v2/1d6cc009162d4bc89ef33344f1584a6a/servers/detail (Caused by <class     
'socket.error'>: [Errno 111] Connection refused)
```

There is a similar problem with Neutron:

```
vagrant@controller:~$ neutron agent-list
Unable to establish connection to http://192.168.100.200:9696/v2.0/agents.json
vagrant@controller:~$ neutron net-list
Unable to establish connection to http://192.168.100.200:9696/v2.0/networks.json
```

whereas Glance is working.

This is with Vagrant 1.7.2 on OS X 10.10.2

**Comment by uksysadmin** [comment]
Has this just happened today? I've just tried building this today and got lots of errors with packages failing to install. As the scripts use Ubuntu 14.04, it also uses Canonical's packages. I'll keep trying. If you notice it's something else, let me know - the configs haven't changed and used to work [this gets spun up daily using these scripts].

**Comment by verdurin** [comment]
Yes, just this afternoon. I did notice some errors flashing past, but it's the first time I've tried your scripts so I wasn't sure which of them might be expected or not...

Is there a logging option for the provisioning stage, so I can see what's failing then?

**Comment by uksysadmin** [comment]
Not directly. I've got a small change I can make to the Vagrant scripts so I can capture the output to a file instead of it flashing by. Will need to test it first.

**Comment by verdurin** [comment]
Okay, I removed the original boxes and re-ran the whole thing. This time it worked - the Nova and Neutron services are working and I was able to login to the demo instance, so as you say this may have been a transient networking problem.

Thanks for the quick response.
