### ISSUE TITLE
Is Ceilometer working?

### ISSUE THREAD

**Issue by verdurin** [OpenStackCookbook/OpenStackCookbook#45]
On the cloud I setup yesterday, the Ceilometer service isn't responding:

vagrant@controller:~$ ceilometer meter-list
Error communicating with http://172.16.0.200:8777 [Errno 111] Connection refused

**Comment by uksysadmin** [comment]
Thanks. We're writing the scripts as we go along with the book, so some parts of the scripts mightn't be fully baked. We generally try and build it all up from the beginning, but some things get chopped and changed as we find better ways of explaining something, and some things break. I'll take a look tomorrow.

**Comment by verdurin** [comment]
Thanks for looking. Not moaning at all - I was in urgent need of a locally-hosted cloud for testing, until I can arrange access to permanent resources and your scripts seemed like the most mature I could find.

**Comment by uksysadmin** [comment]
We'll get a proper fix out as soon as we can - in the meantime:

missing packages: apt-get install python-bson python-pymongo 

/etc/ceilometer/ceilometer.conf [keystone_authtoken] should look like:

[keystone_authtoken]
auth_host = 192.168.100.200
auth_port = 35357
auth_protocol = https
identity_uri = https://192.168.100.200:5000/
auth_uri = https://192.168.100.200:35357/
admin_tenant_name = service
admin_user = ceilometer
admin_password = ceilometer
insecure = True

**Comment by verdurin** [comment]
Okay, thanks. Is it okay to keep reporting these, or am I just slowing you down...?

**Comment by uksysadmin** [comment]
All is good. Reporting is good as we end up having to troubleshoot and fix these things eventually anyway. So thank you.

**Comment by verdurin** [comment]
I just rebuilt all the boxes and I can confirm that with those packages installed and the keystone configuration for Ceilometer added as per the comment above, Ceilometer commands work.
