### ISSUE TITLE
Deploying script with VMware Fusion on OS X hangs on controller node

### ISSUE THREAD

**Issue by JPtheJP** [OpenStackCookbook/OpenStackCookbook#53]
I followed instructions from: https://openstackr.wordpress.com/2014/05/01/openstack-cloud-computing-cookbook-the-icehouse-scripts/#comments
I grabbed the scripts here to install on OS X with Fusion. I have the Vagrant Fusion plug-in.

vagrant up deploys the controller, then the network node remains stuck at "==> network:  * Enabling remote OVSDB managers". Sitting idle for the last 6 hours. Any hint appreciated. 

OS X 10.10.3, VMware Fusion 7.1.1, Vagrant 1.7.2.

**Comment by uksysadmin** [comment]
Hi,
Strangely enough I was trying this myself this evening and have the same
problem. It's noted. I'm working on it.

Kev

On 26 April 2015 at 18:29, JPtheJP <notifications@github.com> wrote:

> I followed instructions from:
> https://openstackr.wordpress.com/2014/05/01/openstack-cloud-computing-cookbook-the-icehouse-scripts/#comments
> I grabbed the scripts here to install on OS X with Fusion. I have the
> Vagrant Fusion plug-in.
>
> vagrant up deploys the controller, then the network node remains stuck at
> "==> network: * Enabling remote OVSDB managers". Sitting idle for the last
> 6 hours. Any hint appreciated.
>
> OS X 10.10.3, VMware Fusion 7.1.1, Vagrant 1.7.2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenStackCookbook/OpenStackCookbook/issues/53>.
>



-- 
Kevin Jackson
http://openstac.kr
@itarchitectkev

**Comment by JPtheJP** [comment]
Nice to know I am not crazy :-)
It appears the network node is in unresponsive state and does not boot properly. I can't reach it from Fusion UI and although there is a process for it, the VM is definitely lost somewhere. Dirty work around: kill the fusion process for the compute node, remove the lock file from the network node VM folder and manually boot the network node (Fusion UI) allows installation to proceed.
I am seeing the compute node being processed now. Let me know if I can help.

**Comment by uksysadmin** [comment]
This is a Fusion issue - this is the fix:

sudo touch "/Library/Preferences/VMware Fusion/promiscAuthorized"

Apparently if you attempted to do the same commands in an interactive session, you will have been prompted to OK to this. That prompt isn't captured/available in a Vagrant headless session.

**Comment by JPtheJP** [comment]
Yes, indeed.
Issue is fixed. Case closed. Thanks a lot for the quick turn around.
