### ISSUE TITLE
Windows as host - PLEASE READ: Authorization Failed: SSL exception connecting to https://192.168.100.200:5000/v2.0/tokens

### ISSUE THREAD

**Issue by pinggit** [OpenStackCookbook/OpenStackCookbook#58]
I'm following the instruction of the book literally, and got stuck in chapter 1 page 7, when I do this:

```
root@controller:/vagrant# keystone tenant-create --name cookbook --description "Default Cookbook Tenant" --enabled true
Authorization Failed: SSL exception connecting to https://192.168.100.200:5000/v2.0/tokens
root@controller:/vagrant#
```
everything before this works exactly like what the book mentioned.

it looks I hit this bug: https://bugs.launchpad.net/python-keystoneclient/+bug/1297280
I'm just wondering how did you workaround it?

thanks.

regards
ping

**Comment by pinggit** [comment]
very annoying...If it's ssl related I hope I can disable ssl (but how?) and move on...

**Comment by uksysadmin** [comment]
We use self-signed certs in the environment. This is explained in the book which is what the environment is used for. Take a look in the openrc file [which is in the directory you typed 'vagrant up'. Here it specifies the path to the self-signed certs. Ensure they're visible to where you're running 'keystone' and other commands. To get around the fact you're seeing a warning about SSL, add '--insecure' to all your commands (or alias all the commands to automatically add this in. See 'demo.sh' for an example of this). If you're getting different SSL errors, please help us track this down so we can fix this for other users. Thanks.

**Comment by pinggit** [comment]
thanks. 
I tried that `--insecure` before, it doesn't work and pop up below messages:

```
root@controller:/vagrant# ls
cakey.pem  ca.pem  Vagrantfile
root@controller:/vagrant# restart keystone
keystone start/running, process 5754
root@controller:/vagrant# 2015-09-29 18:58:17.447 5754 WARNING keystone.openstack.common.versionutils [-] Deprecated: keystone.middleware.core.XmlBodyMiddleware is deprecated as of Icehouse in favor of suppo
rt for "application/json" only and may be removed in Kilo.
2015-09-29 18:58:17.480 5754 WARNING keystone.openstack.common.versionutils [-] Deprecated: keystone.contrib.revoke.backends.kvs is deprecated as of Juno in favor of keystone.contrib.revoke.backends.sql and 
may be removed in Kilo.
root@controller:/vagrant# keystone --insecure user-list
2015-09-29 18:58:27.733 5762 WARNING keystone.common.wsgi [-] Authorization failed. The request you have made requires authentication. from 192.168.100.200
The request you have made requires authentication. (HTTP 401)
```

I hope I can figure this out and help myself, but I'm really a beginner and has no much clues about what was happening here...

**Comment by uksysadmin** [comment]
What OS are you running?
What version of Vagrant?
What version of VirtualBox?

Paste the steps you did to get this far too.

**Comment by pinggit** [comment]
my OS:
```
ping@ubuntu1404:~/openstack/cookbook$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

my vagrant version:
```
ping@ubuntu1404:~/openstack/cookbook$ vagrant -v
Vagrant 1.7.4
```

my version of VirtualBox:
```
4.1.10_r93012
```

the steps I did is just to following the chapter 1:

in controller:
```
sudo apt-get install python-keystoneclient
keystone-manage ssl_setup --keystone-user keystone --keystone-group keystone

sudo cp /etc/keystone/ssl/certs/ca.pem /etc/ssl/certs/ca.pem
sudo c_rehash /etc/ssl/certs/ca.pem
sudo cp /etc/keystone/ssl/certs/ca.pem /vagrant/ca.pem
sudo cp /etc/keystone/ssl/certs/cakey.pem /vagrant/cakey.pem
```

in /etc/keystone/keystone.conf, add these:
```
[ssl]
enable = True
certfile = /etc/keystone/ssl/certs/keystone.pem
keyfile = /etc/keystone/ssl/private/keystonekey.pem
ca_certs = /etc/keystone/ssl/certs/ca.pem
cert_subject=/C=US/ST=Unset/L=Unset/O=Unset/CN=192.168.100.200
ca_key = /etc/keystone/ssl/certs/cakey.pem
```
so the keystone.conf will look like this:
```
root@controller:~# cat /etc/keystone/keystone.conf
[DEFAULT]
admin_token = ADMIN
log_dir=/var/log/keystone
[database]
connection = mysql://keystone:openstack@172.16.0.200/keystone
[extra_headers]
Distribution = Ubuntu
use_syslog = True
syslog_log_facility = LOG_LOCAL0

[ssl]
enable = True
certfile = /etc/keystone/ssl/certs/keystone.pem
keyfile = /etc/keystone/ssl/private/keystonekey.pem
ca_certs = /etc/keystone/ssl/certs/ca.pem
cert_subject = /C=US/ST=Unset/L=Unset/O=Unset/CN=192.168.100.200
ca_key = /etc/keystone/ssl/certs/cakey.pem
```

then restart keystone:
```
sudo stop keystone
sudo start keystone
```

setup environment:
```
export OS_TENANT_NAME=cookbook
export OS_USERNAME=admin
export OS_PASSWORD=openstack
export OS_AUTH_URL=https://192.168.100.200:5000/v2.0/
export OS_NO_CACHE=1
export OS_KEY=/vagrant/cakey.pem
export OS_CACERT=/vagrant/ca.pem
```

now below command will trigger the original errors:
```
keystone tenant-create --name cookbook --description "Default Cookbook Tenant" --enabled true
```

actually any keystone commands will trigger the same. adding "--insecure" will get current errors in my previous post...

b.t.w I run everything as root, if that matters...



if this is hard to workaround at this time and I want to just move on and continue to learn the rest part of the book (I'll come back to here again in my 2nd round study of this book), I'm thinking maybe I should bypass this ssl part if it's doable , but again I don't know how to :( 
thanks.

**Comment by gecchito** [comment]
Hi,
i confirm the issue. I followed literally the book and received the same exact error.

**OS: Windows 10**
**Vagrant version: 1.7.4**
**Virtualbox version: 5.0.6 r103037**

During troubleshooting, i found an error in keystone.conf; there were two connection strings under _[database]_ section. One was the book string that i put on first row, the other one was the default for sqlite. This problem didn't allow the creation of tables in keystone database. Solved this problem by commenting the sqlite row.
Now i tried to bypass the authentication by defining, as suggested in Openstack installation manual, the OS_SERVICE_TOKEN and OS_SERVICE_ENDPOINT variables and adjusting the keystone.conf accordingly.
The error i receive now is:

`root@controller:/etc/keystone# keystone --debug tenant-create --name cookbook --description "Default Cookbook Tenant" --enabled true`
`WARNING: Bypassing authentication using a token & endpoint (authentication credentials are being ignored).`
`DEBUG:keystoneclient.session:REQ: curl -i -X POST https://192.168.100.200:5000/v2.0/tenants -H "User-Agent: python-keystoneclient" -H "Content-Type: application/json" -H "X-Auth-Token: 70d24aea588fd7048880" -d '{"tenant": {"enabled": true, "name": "cookbook", "description": "Default Cookbook Tenant"}}'`
`INFO:urllib3.connectionpool:Starting new HTTPS connection (1): 192.168.100.200`
`DEBUG:urllib3.connectionpool:Setting read timeout to 600.0`
`DEBUG:urllib3.connectionpool:"POST /v2.0/tenants HTTP/1.1" 404 93`
`DEBUG:keystoneclient.session:RESP:`
`DEBUG:keystoneclient.session:Request returned failure status: 404`
`The resource could not be found. (HTTP 404)`

Thank you in advance for any help.

**Comment by uksysadmin** [comment]
The common element is Windows. All development was done using a *nix based host, so problems like yours might be because we haven't catered for this environment.
That said - we welcome forks and patches. I'll have a look at the SQL line to confirm too.
Also, please ensure that you can no errors occurred during installation (when you did vagrant up)? 
Also when you "vagrant ssh controller" can you confirm you can see /vagrant directory - which is exported from the host to the controller. If you can't, then that is why you aren't reading the cert files (see openrc file for why this is the case).

**Comment by gecchito** [comment]
Hi, 
i had no problems in Vagrant installation. When i issued `vagrant up` from cmd, all started correctly.
As for now i log in on controller host, using the management IP (172.16.0.200) and puTTY.
I was a bit lazy (not setting %PATH% in Windows to puTTY), because i was eager to delve in Openstack :).
I can confirm that i see the `/vagrant` directory, otherwise i surely had problems during the `cp` steps just a little back in the installation procedure (the page before on your book).
Just another information: i have a slightly different path for `cakey.pem`.
In particular my path is: `/etc/keystone/ssl/private/cakey.pem`, but i googled and i found that other users have the same path, hence shouldn't be a problem.

Thank you very much and keep up the good work.

**Comment by piquesel** [comment]
I have the exact same problem here on my Windows 7 + Virtualbox-5.0.6 + Vagrant-1.7.4. Any solution found to use ssl?

In the meantime, I don't use authentication as shown in previous release of the book:
vagrant@controller:~$ export ENDPOINT=192.168.100.200
vagrant@controller:~$ export SERVICE_TOKEN=ADMIN
vagrant@controller:~$ export SERVICE_ENDPOINT=http://${ENDPOINT}:35357/v2.0
vagrant@controller:~$ keystone tenant-create --name cookbook --description "Default Cookbook Tenant" --enable=true

Thanks.

**Comment by uksysadmin** [comment]
Just add --insecure to any of your client commands. There is obviously a problem with the environment when Windows is the host. Under *nix as the place where VirtualBox is installed, we use NFS to mount stuff between host and Guest. Under Windows this isn't natively available, so I'm assuming at some point during the install it doesn't copy something over.

**Comment by inn3rbr4in** [comment]
Hello,
I have exactly the same problem. I tried configuration on both Windows 7 that on CentOS release 6.7.

In both installations I used last release of Vagrant and Virtual Box 4.3.34.
The test release of OpenStack is kilo.

Please check, because it does not seem to be a windows problem but a configuration problem.

I watched a lot of documentations and following the official documentation I tried also to configure [eventlet_server_ssl] session without succes.

Another detail: the "keystone-manage ssl_setup" command require sudo.

Thanks

**Comment by inn3rbr4in** [comment]
Following more informations:

The command I used to generate keys:
```
sudo keystone-manage ssl_setup --rebuild --keystone-user keystone --keystone-group keystone
sudo cp /etc/keystone/ssl/certs/ca.pem /etc/ssl/certs/ca.pem
sudo c_rehash /etc/ssl/certs/ca.pem

```

The list of export that I used:
```
export OS_TENANT_NAME=cookbook
export OS_USERNAME=admin
export OS_PASSWORD=openstack
export OS_AUTH_URL=https://192.168.100.200:5000/v2.0/
export OS_NO_CACHE=1
export OS_KEY=/vagrant/cakey.pem
export OS_CACERT=/vagrant/ca.pem
```

And because is the first time the I use keystone
```
export ENDPOINT=192.168.100.200
export SERVICE_TOKEN=ADMIN
export SERVICE_ENDPOINT=https://${ENDPOINT}:35357/v2.0
export OS_KEY=/vagrant/cakey.pem
export OS_CACERT=/vagrant/ca.pem
```

The /etc/keystone/keystone.conf ssl configuration. NOTE: cakey.pem is in ssl/private directory
```
[ssl]
enable = True
certfile = /etc/keystone/ssl/certs/keystone.pem
keyfile = /etc/keystone/ssl/private/keystonekey.pem
ca_certs = /etc/keystone/ssl/certs/ca.pem
cert_subject=/C=US/ST=Unset/L=Unset/O=Unset/CN=192.168.100.200
ca_key = /etc/keystone/ssl/private/cakey.pem
```

The error
```
vagrant@controller:/vagrant$ keystone tenant-create --name cookbook --description "Default Cookbook Tenant" --enabled true
WARNING: Bypassing authentication using a token & endpoint (authentication credentials are being ignored).
SSL exception connecting to https://192.168.100.200:35357/v2.0/tenants
```

**Comment by inn3rbr4in** [comment]
Hello,
after a lot of time spent on researches I found a workaround that can solve this problem based on [official documentation](http://docs.openstack.org/kilo/install-guide/install/yum/content/keystone-install.html)

With Kilo and newest releases is recommended to use Apache plus mod_wsgi module (in substitution of eventlet server).

First of all install MariaDB and follow the steps in book up to page 4.

Below the steps to install Apache plus mod_wsgi module:
```
sudo stop keystone
sudo apt-get install -y apache2
sudo apt-get install -y libapache2-mod-wsgi
```
Create the wsgi-keystone.conf file
```
sudo vim /etc/apache2/sites-available/wsgi-keystone.conf
```
Below my file wsgi-keystone.conf:
```
Listen 5000
Listen 35357

<VirtualHost 192.168.100.200:5000>
    WSGIDaemonProcess keystone-public processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP}
    WSGIProcessGroup keystone-public
    WSGIScriptAlias / /var/www/cgi-bin/keystone/main
    WSGIApplicationGroup %{GLOBAL}
    WSGIPassAuthorization On
    LogLevel info
    ErrorLogFormat "%{cu}t %M"
    ErrorLog /var/log/httpd/keystone-error.log
    CustomLog /var/log/httpd/keystone-access.log combined
    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/apache.crt
    SSLCertificateKeyFile /etc/apache2/ssl/apache.key
</VirtualHost>

<VirtualHost 192.168.100.200:35357>
    WSGIDaemonProcess keystone-admin processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP}
    WSGIProcessGroup keystone-admin
    WSGIScriptAlias / /var/www/cgi-bin/keystone/admin
    WSGIApplicationGroup %{GLOBAL}
    WSGIPassAuthorization On
    LogLevel info
    ErrorLogFormat "%{cu}t %M"
    ErrorLog /var/log/httpd/keystone-error.log
    CustomLog /var/log/httpd/keystone-access.log combined
    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/apache.crt
    SSLCertificateKeyFile /etc/apache2/ssl/apache.key
</VirtualHost>
```
Enable Virtual Host and make cgi directory
```
sudo a2ensite wsgi-keystone
sudo mkdir -p /var/www/cgi-bin/keystone
```
Now you need to create Python script for Apache (admin and main). I followed the official documentation without success for this I used  the [instructions provided by Matt Dorn](https://developer.rackspace.com/blog/configure-keystone-apache/).
Create two file /var/www/cgi-bin/keystone/main and /var/www/cgi-bin/keystone/admin with the following content:
```
import logging
import os

from paste import deploy

from keystone.openstack.common import gettextutils
# NOTE(dstanek): gettextutils.enable_lazy() must be called before
# gettextutils._() is called to ensure it has the desired lazy #lookup behavior. This includes cases, like keystone.exceptions, #where gettextutils._() is called at import time.
gettextutils.enable_lazy()

from keystone.common import dependency
from keystone.common import environment
from keystone.common import sql
from keystone import config
from keystone.openstack.common import log
from keystone import service


CONF = config.CONF

config.configure()
sql.initialize()
config.set_default_for_default_log_levels()

CONF(project='keystone')
config.setup_logging()

environment.use_stdlib()
name = os.path.basename(__file__)

if CONF.debug:
    CONF.log_opt_values(log.getLogger(CONF.prog), logging.DEBUG)


drivers = service.load_backends()

# NOTE(ldbragst): 'application' is required in this context by WSGI spec.
# The following is a reference to Python Paste Deploy documentation
# http://pythonpaste.org/deploy/
application = deploy.loadapp('config:%s' % config.find_paste_config(),
                         name=name)

dependency.resolve_future_dependencies()
```
Now you can disable keystone service (now keystone it's provided by Apache). Edit /etc/init/keystone.conf and comment (#) this row
```
start on runlevel [2345]
```
Change permissions and enable ssl module
```
sudo chown -R keystone:keystone /var/www/cgi-bin/keystone
sudo chmod 755 /var/www/cgi-bin/keystone/*
sudo mkdir /var/log/httpd
sudo a2enmod ssl
sudo mkdir /etc/apache2/ssl
```
Now you can create CA certificate and certificate for server
```
openssl genrsa -out /etc/apache2/ssl/cakey.pem 2048

openssl req -x509 -new -nodes -key /etc/apache2/ssl/cakey.pem -days 3650 -out /etc/apache2/ssl/cacert.pem

Country Name (2 letter code) [AU]:US
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:
Email Address []:

openssl genrsa -out /etc/apache2/ssl/apache.key 2048

openssl req -new -key /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.csr

Country Name (2 letter code) [AU]:US
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:192.168.100.200
Email Address []:

openssl x509 -req -in /etc/apache2/ssl/apache.csr -CA /etc/apache2/ssl/cacert.pem -CAkey /etc/apache2/ssl/cakey.pem -CAcreateserial -out /etc/apache2/ssl/apache.crt -days 3560
```

Now it's important to add the CA certificate to the trust authorities. The same step it's described in book page 6 but I have the suspect that the procedure shown not work well (and this could be the source of the problem described in the thread, but I have not had time to try). For this I followed another procedure:
```
sudo cp /etc/apache2/ssl/cacert.pem /etc/apache2/ssl/cacert.csr
sudo update-ca-certificates
```
Now you can restart Apace
```
sudo service apache2 restart
```

__NOTE__: you can see some warning in /var/log/httpd/keystone-error.log. I tried to solve them without success but the Apache server works with SSL without problem

Now you can test new service. To do this I suggest to install openstack client that substitute keystone client (deprecated).

Following the steps up to page 14 written for the new command (use the [official doc](http://docs.openstack.org/developer/python-openstackclient/) of open stack for command syntax):
```
export OS_TOKEN=ADMIN
export OS_URL=https://192.168.100.200:35357/v2.0
openstack project create --description "Default Cookbook Tenant" cookbook
openstack project create --description "Admin Tenant" admin
openstack project list
openstack role create admin
openstack role create Member
openstack user create --project cookbook --password openstack --email root@localhost admin
openstack role add --project cookbook --user admin admin
openstack role add --project admin --user admin admin
openstack user create --project cookbook --password openstack --email root@localhost demo
openstack role add --project cookbook --user demo Member
```

I tested everything on Virtualbox deployed on Windows.

Bye

**Comment by uksysadmin** [comment]
This should all be working now.
Turns out checking out Unix files on Windows mangles the LF with a CRLF. Fixed this.
Current setup known to work: Windows 10, VirtualBox 5.012, Vagrant 1.8.1. Enjoy!

**Comment by achisti** [comment]
"Current setup known to work: Windows 10, VirtualBox 5.012, Vagrant 1.8.1. Enjoy!" 
I'm still getting the same SSL authentication error as was reported at the beginning of the file. So how did the error go away? What are the steps taken.

**Comment by crevitch** [comment]
I get this error at the tenant create step.
Authorization Failed: SSL exception connecting to https://192.168.100.200:5000/v2.0/tokens
However, I am on centos 6.6.
I also noticed that the /etc/keystone/ssl/private/cakey.pem is in the private directory.  I made the approriate changes for that.  Any ideas on what to try to fix this?

**Comment by ldmtam** [comment]
Anyone can fix this problem? Please tell me .

**Comment by paulphoenix01** [comment]
@uksysadmin  can you please elaborate on this issue ? I follow all the steps as in the book, or try again with the steps of @inn3rbr4in, but still the same issue.

**Comment by piquesel** [comment]
For what it's worth as this thread is rather old and if some people are still trying to learn using OpenStack Cloud Computing Cookbook.
I think there's a big misunderstanding in this thread. As mentioned by other people, this has nothing to do with Windows, Mac or whatever environment. I'm using Ubuntu and I stumble across the same problem.
If you follow the instructions on [this page from the website](https://openstackcookbook.com/2015/03/28/openstack-clients-installation-on-ubuntu-for-the-openstack-cloud-computing-cookbook/), you'll notice there's a section called: Configuring Keystone for the first time.
It gives the proper configuration to by-pass the authentication: "This bypasses the usual authentication process to allow services and users to be configured in Keystone before the users and passwords exist."
Once you've done that, you can progress in the book and you'll just get a warning that authentication has been disabled.
Once you've created your users, tenants, roles etc. you can get back to this and remove the specific settings to by-pass authentication. It will then leverage SSL features correctly.
At least that's my understanding and it seems to work for me ;).
