### ISSUE TITLE
should not use ifconfig anymore... use ip link

### ISSUE THREAD

**Issue by flavio-fernandes** [OpenStackCookbook/OpenStackCookbook#63]
on page 64:

instead of:
   sudo ifconfig ethX down
   sudo ifconfig ethX 0.0.0.0 up

you should do:
     sudo ip addr flush dev ethX
     sudo ip link set ethX up

**Comment by uksysadmin** [comment]
We update according to what is available at the time of submission and check all is working.
Whilst ip a is preferred and ifconfig is going to removed in a future release, it is still perfectly valid for the ubuntu 14.04 LTS release so ifconfig still works. Will update when required.
