### ISSUE TITLE
Glance image-create report Authorization Failed: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by kenkensh** [OpenStackCookbook/OpenStackCookbook#64]
I follow the openstack clouding computing 2nd edition book to deloy, at 2nd chapter, the glance can't work as wish. 
no information in api.log and registry.log. even in keystone log.  what is the failure meaning, glance can't communication with keystone? but keystone is work fine. 
I google the issue but no any clue. 
even I run glance index, same issue. I double check the .conf and .ini file. it is same with book's description. 

any help?

**Comment by kenkensh** [comment]
add env description:

windows 7 
virtualbox  4.2.16
vagrant 1.2.7

**Comment by kenkensh** [comment]
I reset all env, it seems some typo in book. now it can going on

**Comment by uksysadmin** [comment]
Note the 2nd edition is out of date - the code might be invalid. We no longer support/maintain this [it's based on Grizzly]. Use the 3rd Edition / Master repo [this is Juno].
