### ISSUE TITLE
invalid metadata: The `name' attribute is required in cookbook metadata

### ISSUE THREAD

**Issue by kenkensh** [OpenStackCookbook/OpenStackCookbook#68]
now running into issue when execute the chef lab

vagrant@chef:~$ sudo knife cookbook upload -o /root/cookbooks --all
ERROR: Chef::Exceptions::MetadataNotValid: Cookbook loaded at path(s) [/root/cookbooks/data_bags] has invalid metadata: The `name' attribute is required in cookbook metadata

**Comment by uksysadmin** [comment]
We don't use Chef. Can you check what version you're using?
Master is currently Juno which is the version aligned to the book.

Kev

On 8 January 2016 at 15:23, kenkensh <notifications@github.com> wrote:

> now running into issue when execute the chef lab
>
> vagrant@chef:~$ sudo knife cookbook upload -o /root/cookbooks --all
> ERROR: Chef::Exceptions::MetadataNotValid: Cookbook loaded at path(s)
> [/root/cookbooks/data_bags] has invalid metadata: The `name' attribute is
> required in cookbook metadata
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenStackCookbook/OpenStackCookbook/issues/68>.
>



-- 
Kevin Jackson
http://openstac.kr
@itarchitectkev

**Comment by uksysadmin** [comment]
This is invalid. Wrong perception of what the OpenStack Cloud Computing Cookbook (a book) is.
