### ISSUE TITLE
Windows 7 - mount vboxsf fails

### ISSUE THREAD

**Issue by brahmastra2016** [OpenStackCookbook/OpenStackCookbook#75]
in windows environment the vagrant up command fails to mount share folder.

#####
Error:
#####

Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

###
Fix:
###

1) After the VM boots  - login to the VM and issue below command

        a) sudo ln -sf /opt/VBoxGuestAdditions-5.1.20/lib/VBoxGuestAdditions/mount.vboxsf /sbin/mount.vboxsf

      b) vagrant reload

Note: You will have to do it for each VM , since it will fail each of VM it try to boot up

**OR**

2) Create you own base box with the fix and use that base in the vagrantfile.
      
      https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one

**Comment by englishli** [comment]
Hi

 May I know if you complete all the openstack 's lab fllowing the book's guide? It seems a lot confuse for me to following the operation, especially the neutron's part. 

 could you share your script which could help to sucessfully to deploy all kind of stuff? VM image is better. Thanks in advanced.

**Comment by uksysadmin** [comment]
The 3rd edition of the book was written for Juno/Kilo and the steps were correct at time of publishing and we have been trying to keep it relevant. However Kilo is now EOL. We are working on a new book and a new environment - see https://github.com/OpenStackCookbook/vagrant-openstack/ for an updated environment.
