### ISSUE TITLE
Vagrant Box : 'bunchc/trusty-x64'  seems to be no longer available ?  

### ISSUE THREAD

**Issue by ColumGaynor** [OpenStackCookbook/OpenStackCookbook#76]
`
gaynor@gaynor-Aspire-E5-521:~/OpenStackCookbook$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bunchc/trusty-x64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bunchc/trusty-x64'
    default: URL: https://atlas.hashicorp.com/bunchc/trusty-x64
==> default: Adding box 'bunchc/trusty-x64' (v0.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/bunchc/boxes/trusty-x64/versions/0.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
`

**Comment by ColumGaynor** [comment]
CG: June 2dn 2017: 
        Delighted to report, the issue is fixed and can be CLOSED. 
        I was missing one needed package: after which everything worked perfectly.
        Thank you Cody Bunch for professional prompt assistance.
        ===>   Needed to execute : "sudo apt-get install nfs-common"
        -Colum

On 31.5.2017, Cody Bunch wrote:

      So I did a thing. 
      It took a little bit more work than I had anticipated, but, my originals are back online. 
      Let me know if you encounter any trouble.
      
      -C

--------------------------------------------------------------------------------------------------------------
On Tue, May 30, 2017 at 6:28 PM, Cody Bunch <bunchc@gmail.com> wrote:

    An update:

    Ran a quick build with the official ubuntu image ubuntu/trusty64. It successfully built the controller
    under virtual box. I attempted a VMware run, but the official images do not provide a vmware image,
    so that did not work.

    At this time, I'm rebuilding the images using my original packer bundle, updated for 14.04.5, 
    better network drivers, and should have Atlas updated at some point this evening.

    Thanks for hanging in there.
    -C

    On Tue, May 30, 2017 at 3:36 PM, Cody Bunch <bunchc@gmail.com> wrote:

        Hello!

        Thanks for reaching out. 
        I'm sorry the box as gone missing. 
        The long and short of it, is I am apparently bad at the cloud.

        To solve your specific problem, there are a few approaches. 
        The first and fourth are likely the best of the bunch.

        1) Substitute the box in the Vagrantfile - 
            This /should/ work, but you may encounter missing ubuntu packages. 
            While time consuming, a few "apt-get install" commands would help you across the gap.

        2) Rebuild the box - The original packer config files are hosted on git
            (https://github.com/OpenStackCookbook/OpenStackCookbook/tree/master/packer) 
             and were how we built the images for the book.

        3) We are actively working on a 4th edition. 
             While that's a few months out at this point, will have an updated lab and lots of new 
             operations focused materials (and likely less broken boxes).

        4) Check back on the box in a few days time. I'm going to attempt a rebuild and to host it again.

        On Tue, May 30, 2017 at 3:03 PM, Colum Gaynor <columgaynor@gmail.com> wrote:

            https://atlas.hashicorp.com/bunchc/boxes/trusty-x64

            vagrant init bunchc/trusty-x64; vagrant up --provider virtualbox
            Hi,

            Bought the PACKT book "OpenStack Cloud Computing Cookbook - Third Edition"
            Tried to use the Vagrant file from associated github site but the vagrant box 
             "bunchc/trusty-x64" seems to be missing.

            Question: Can it be simply substituted by available Ubuntu Trusty-x64 boxes now found on
            atlas.hashicorp.com
            New to all this and thanks for any help you could advice.

            Regards Colum

**Comment by jcmoreno** [comment]
Hi, 

I'm getting something similar. I'm getting:

```
root@os:/opt/OpenStackCookbook# vagrant up
Bringing machine 'controller' up with 'virtualbox' provider...
Bringing machine 'network' up with 'virtualbox' provider...
Bringing machine 'compute-01' up with 'virtualbox' provider...
Bringing machine 'cinder' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'bunchc/trusty-x64' could not be found.
```

Can you please advise?

Thank you!

**Comment by ColumGaynor** [comment]
@jcmoreno : I needed to set this OpenStack CookBook onto a new test machine installed with Ubuntu 16.04 (latest updates etc).  I know this will be a mystery for you maybe, but IT WORKED! The needed box was restored (as reported above) by Cody Bunch and I can definitely confirm the whole vagrant based installation worked for me today. The only special actions I needed were not really related to the original issue of missing boxes.  

Special actions needed:
1. Removed version 1.8.1 of vagrant which comes with Ubuntu 16.04 repository and downloaded from Vagrant Web Site the current version 1.9.5   This allows the recommened step: "vagrant plugin install vagrant-cachier" to work. (There is an known issue in version 1.8.1 which causes the plugin installation to fail)
2. You need to have the nfs-kernel-server package installed: "sudo apt-get install nfs-kernel-server" .
This package was not installed in fresh Ubuntu 16.04 install.

After this everything worked. Takes a long time but it should bring in and deploy openstack software to four seprate Virtual Machines ( controller, network, compute-01 and cinder ). You need to follow some recommended steps in the book to set some interfaces to be enslaved in relevant bridges. I took a session to the Horizon GUI and it worked. Will play with the set-up soon and report any issues but so far it looks to be OK.   I also checked the Vagrant BOx Repository site: https://app.vagrantup.com/bunchc/boxes/trusty-x64 and Cody Bunch's box is clearly seen there. Earlier there were warnings reported that the box was missing.

Try again and let me know if you still have issues to get it working.
Sorry delayed response - summer vacation ongoing!

Regards Colum  (columgaynor@gmail.com)

**Comment by jcmoreno** [comment]
Awesome thx. I'll test this!
