### ISSUE TITLE
issue with neutron service and software package installation

### ISSUE THREAD

**Issue by englishli** [OpenStackCookbook/OpenStackCookbook#79]
Hi,
two issue I found:
First, Iif I follow the book, it seems that in neutron chapter , it will use OVS VXLAN and GRE, but at the same time the controller just use ML2 plugin with OVS.
secondly, more dispointed point for me is that computer chapter in 3rd edition don't mention the neutron software package's installation such as openvsitch etc, which means we can't compelete the openstack's lab if we follow this great book step by step even I git the  code to understand the script, but more confuse me is that compute.sh don't match with the chapter 4 Nova 's content.
I am not sure where is the clear and total script or code can help me to sucessfully handle this great openstack book.
any idea?  Thanks in advance for any help
Thanks.

**Comment by uksysadmin** [comment]
The code that the book refers to is no longer supported by the community and as such the steps described in the 3rd edition may not be 100% accurate now. Kilo was EOL in May 2016. https://releases.openstack.org/. I suggest looking at our new environment that uses Ansible to create a more "version agnostic" way (to a certain degree) of installing and upgrading OpenStack. The last chapter of the 3rd edition introduces you to the OpenStack Ansible project and we use this as a foundation for the new book.
