### ISSUE TITLE
could someone share the test VM?

### ISSUE THREAD

**Issue by englishli** [OpenStackCookbook/OpenStackCookbook#80]
Hi,

  I am wondering if anyone compelte the openstack lab step by step follow the 3rd editon. if there is, could you share the  virtuabox VM which complete all labs, so we can import into our enviorment to learn more about the openstack's theory and experience it more effectively.

  base on this point, I am call for the sharing of the VM image from authors ( I do think they do all these thing already) which include all the labs's operation in this great book.  

 Just my coin.  Thanks.

**Comment by uksysadmin** [comment]
See the other comment. This book was written for Juno/Kilo. As OpenStack produces a new version of code every 6 months, Kilo is EOL which means the configuration options may have change.
We strongly recommend you look at https://github.com/OpenStackCookbook/vagrant-openstack/ for the updated version of our lab environment and the updated use of Ansible to get this deployed. This is to accompany the 4th edition of the book which is work in progress, due end of the year.
